apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-db-creds
  namespace: spring
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "database"          # Kubernetes auth role
    objects: |
      - objectName: "db-username"
        secretPath: "database/creds/my-role"
        secretKey: "username"

      - objectName: "db-password"
        secretPath: "database/creds/my-role"
        secretKey: "password"
