# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: vault-db-creds
#   namespace: spring
# spec:
#   provider: vault
#   parameters:
#     vaultAddress: "http://vault.vault:8200"
#     roleName: "database"          # Kubernetes auth role
#     objects: |
#       - objectName: "db-username"
#         secretPath: "database/creds/my-role"
#         secretKey: "username"

#       - objectName: "db-password"
#         secretPath: "database/creds/my-role"
#         secretKey: "password"


# //////////////////


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: spring
spec:
  provider: vault
  secretObjects:
  - secretName: db-credentials     
    type: Opaque
    data:
      - key: username               
        objectName: db-username
      - key: password               
        objectName: db-password
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "database"
    objects: |
      - objectName: "db-username"
        secretPath: "database_2/creds/role_2"
        secretKey: "username"

      - objectName: "db-password"
        secretPath: "database_2/creds/role_2"
        secretKey: "password"
