# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: vault-database
#   namespace: spring
# spec:
#   provider: vault
#   parameters:
#     vaultAddress: "http://vault.vault:8200"
#     audience: "https://kubernetes.default.svc"
#     roleName: "database"
#     objects: |
#       - objectName: "db-password"
#         secretPath: "db-pass/data/db-pass"
#         secretKey: "password"


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
  namespace: spring
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "database"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-pass"
        secretKey: "password"

