apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: postgress
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner   Nnp731xR4l6hbneRshrNMG5apEfBAWao0abmzFbiZ4nIWkpcZthCO7Wo5Y1bnWkW
  preparedDatabases:
    bar: {}
  postgresql:
    version: "17"