apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster2
  namespace: postgress
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    zalando2:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo2: zalando2  # dbname: owner   u53zk8jVAGlDZmmv6zaMhwSIBnNk9RdjETOfwHTb3hqa8dOEXYSW1uPYkkebrWm0
  preparedDatabases:
    bar: {}
  postgresql:
    version: "17"
